# Generated by Django 6.0.7 on 2026-07-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
